### ISSUE TITLE
Use Heroku for Deployment

### ISSUE THREAD

**Issue by Yash-Singh1** [browserslist/browserl.ist#285]
[Heroku](heroku.com) is an almost completely free server-hosting solution. I think that browserl.ist should be hosted on Heroku. Custom domains are available in the free edition.

**Comment by ai** [comment]
What about privacy? Do they have a guarantee that they do not track users?

**Comment by ai** [comment]
The main problem with this website is not hosting. I have a solid and almost free solution, which I use for [logux.io](https://logux.io) and [postcss.org](https://postcss.org/).

The problem is that I need to spend time to review pull requests and fix bugs. Because I am sending a few hours every day for PostCSS 8 I do not have time for Browserslist in next month,

For instance, recent PR of [moving project to Vercel](https://github.com/browserslist/browserl.ist/pull/279) took a day with problems at my work.

**Comment by Yash-Singh1** [comment]
Heroku has a git-based framework.

**Comment by Yash-Singh1** [comment]
Every server I host, I work with Heroku.

**Comment by ai** [comment]
> Heroku has a git-based framework. You just need to click a button and run git push to that application. Also, it has a button for connecting to github.

Yeap. I have the same git-based system for [logux.io](https://logux.io) and [postcss.org](https://postcss.org/). The same thing in Vercel.

But you will need a day to make it works correctly. For Vercel I send a day even if Vercel has that auto-git-deploy.

**Comment by Yash-Singh1** [comment]
Yes, it does take some time to set up something like the vercel bot.
